export const MyNewTheme: themeConfig = {
	name: "my-new-theme",
	colors: ["#4c7497", "#85af47"],
	scene: "./assets/scene.gif",
	obstacles: [
		{
			// castle
			a: { x: 819, y: 469 },
			b: { x: 819, y: 629 },
			c: { x: 1100, y: 629 },
			d: { x: 1100, y: 469 },
		},
	],
	players: [
		{
			default: {
				n: "./assets/p1_n.gif",
				ne: "./assets/p1_ne.gif",
				e: "./assets/p1_e.gif",
				se: "./assets/p1_se.gif",
				s: "./assets/p1_s.gif",
				sw: "./assets/p1_sw.gif",
				w: "./assets/p1_w.gif",
				nw: "./assets/p1_nw.gif",
			},
			move: {
				n: "./assets/p1_n.gif",
				ne: "./assets/p1_ne.gif",
				e: "./assets/p1_e.gif",
				se: "./assets/p1_se.gif",
				s: "./assets/p1_s.gif",
				sw: "./assets/p1_sw.gif",
				w: "./assets/p1_w.gif",
				nw: "./assets/p1_nw.gif",
			},
			attack: {
				n: "./assets/p1_n.gif",
				ne: "./assets/p1_ne.gif",
				e: "./assets/p1_e.gif",
				se: "./assets/p1_se.gif",
				s: "./assets/p1_s.gif",
				sw: "./assets/p1_sw.gif",
				w: "./assets/p1_w.gif",
				nw: "./assets/p1_nw.gif",
			},
			block: {
				n: "./assets/p1_n.gif",
				ne: "./assets/p1_ne.gif",
				e: "./assets/p1_e.gif",
				se: "./assets/p1_se.gif",
				s: "./assets/p1_s.gif",
				sw: "./assets/p1_sw.gif",
				w: "./assets/p1_w.gif",
				nw: "./assets/p1_nw.gif",
			},
		},
		{
			default: {
				n: "./assets/p2_n.gif",
				ne: "./assets/p2_ne.gif",
				e: "./assets/p2_e.gif",
				se: "./assets/p2_se.gif",
				s: "./assets/p2_s.gif",
				sw: "./assets/p2_sw.gif",
				w: "./assets/p2_w.gif",
				nw: "./assets/p2_nw.gif",
			},
			move: {
				n: "./assets/p2_n.gif",
				ne: "./assets/p2_ne.gif",
				e: "./assets/p2_e.gif",
				se: "./assets/p2_se.gif",
				s: "./assets/p2_s.gif",
				sw: "./assets/p2_sw.gif",
				w: "./assets/p2_w.gif",
				nw: "./assets/p2_nw.gif",
			},
			attack: {
				n: "./assets/p2_n.gif",
				ne: "./assets/p2_ne.gif",
				e: "./assets/p2_e.gif",
				se: "./assets/p2_se.gif",
				s: "./assets/p2_s.gif",
				sw: "./assets/p2_sw.gif",
				w: "./assets/p2_w.gif",
				nw: "./assets/p2_nw.gif",
			},
			block: {
				n: "./assets/p2_n.gif",
				ne: "./assets/p2_ne.gif",
				e: "./assets/p2_e.gif",
				se: "./assets/p2_se.gif",
				s: "./assets/p2_s.gif",
				sw: "./assets/p2_sw.gif",
				w: "./assets/p2_w.gif",
				nw: "./assets/p2_nw.gif",
			},
		},
	],
	turnSprites: false,
	shader: (ctx: CanvasRenderingContext2D) => {
		ctx.shadowColor = "rgba(0,0,0,0.3)";
		ctx.shadowOffsetX = 2;
		ctx.shadowOffsetY = 2;
		ctx.shadowBlur = 5;
	},
	bgAudio: "./assets/bg.mp3",
	attackAudio: "./assets/attack.mp3",
	blockAudio: "./assets/block.mp3",
};
