export const MyNewTheme: themeConfig = {
	name: "my-new-theme",
	scene: "./assets/scene.gif",
	obstacles: [],
	players: [
		{
			default: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
			move: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
			attack: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
			block: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
		},
		{
			default: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
			move: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
			attack: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
			block: {
				n: "./assets/player_n.gif",
				ne: "./assets/player_ne.gif",
				e: "./assets/player_e.gif",
				se: "./assets/player_se.gif",
				s: "./assets/player_s.gif",
				sw: "./assets/player_sw.gif",
				w: "./assets/player_w.gif",
				nw: "./assets/player_nw.gif",
			},
		},
	],
	turnSprites: false,
	shader: (ctx: CanvasRenderingContext2D) => {
		ctx.shadowColor = "rgba(0,0,0,0.3)";
		ctx.shadowOffsetX = 2;
		ctx.shadowOffsetY = 2;
		ctx.shadowBlur = 5;
	},
	bgAudio: "./assets/bg.mp3",
	attackAudio: "./assets/attack.mp3",
	blockAudio: "./assets/block.mp3",
};
